DROP DATABASE IF EXISTS Proyecto_Integrador;
CREATE DATABASE Proyecto_Integrador;
USE Proyecto_Integrador;

CREATE TABLE IF NOT EXISTS leds(
    led1 TINYINT DEFAULT 1  COMMENT 'estado led 1',
    led2 TINYINT DEFAULT 1  COMMENT 'estado led 2',
    led3 TINYINT DEFAULT 1  COMMENT 'estado led 3',
    led4 TINYINT DEFAULT 1  COMMENT 'estado led 4'
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE = UTF8_SPANISH_CI;

CREATE TABLE IF NOT EXISTS sensores( 
    id INT AUTO_INCREMENT, 
    fecha DATE NOT NULL, 
    hora TIME NOT NULL, 
    sensor VARCHAR(32) NOT NULL, 
    vulue FLOAT NOT NULL, 
    PRIMARY KEY (id) 
)ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE = UTF8_SPANISH_CI

INSERT INTO leds VALUES(0,0,0,0);